# Generated by Django 3.0.4 on 2020-03-22 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.05, message='Preco minimo eh 5 centavos')], verbose_name='Price')),
                ('code', models.IntegerField(verbose_name='BarCode')),
            ],
        ),
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('products', models.ManyToManyField(related_name='Products', to='products.Product')),
            ],
        ),
    ]
