# Generated by Django 3.0.4 on 2020-03-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200322_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermarket',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='Products', to='products.Product'),
        ),
    ]
