# Generated by Django 3.0.4 on 2020-03-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200322_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Name'),
        ),
    ]
